In [1]:
from EEG.preprocessing import aligner_exp

In [3]:
root = "C:\\eeg\\01exp\\"
name = "20161129_DBS_001"

test = aligner_exp(root + name)
flag = test.align(250,250)

print flag
test.getinfo()
test.save(mode = 'data')

True
Experiment status:  True ; Num tests:  12
Align status:  True
Respondent name:  Ольга Ветрова
Description: Эксперимент с обратной связью
Labels_names: [ удалено, отдых, левая, правая ]
Frequency: 1000
Count train activities:  45
Count tests activities: [ 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30 ]
Time of activity: 4500
Type_chanels: eeg  Montage: standard_1005
------------------------------------------------------------------
Chanels_names:
------------------------------------------------------------------
FC5        FT7        FC3        FCz        FC4        FT8       
T3         C3         Cz         T4         C4        
TP7        CP3        CPz        CP4        TP8       
FC1        FC2        FC6        P4         C5        
C1         C2         C6         P3         CP5       
CP1        CP2        CP6        POz       
------------------------------------------------------------------
List tests
------------------------------------------------------------------
20

In [3]:
name = "20161105_OLT_001"

test = aligner_exp(root + name)
flag = test.align(250,250)

print flag
test.getinfo()
test.save()

False
Experiment status:  False ; Num tests:  0
Align status:  False
------------------------------------------------------------------
Ошибки сборки: 
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов
не пройдена проверка на наличие всех файлов

------------------------------------------------------------------


In [12]:
import numpy as np
a=np.random((2,3,5))

TypeError: 'module' object is not callable

In [85]:
x,y,z = 2,4,8
a=np.arange(x*y*z).reshape(2,4,8)
print a

[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]]

 [[32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47]
  [48 49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62 63]]]


In [106]:
new_arr = np.array([])
for idx, i in enumerate(a):
    new_row = np.array([])
    for idy, z in enumerate(i):
        print "row2: ",a[idx][idy]

row2:  [0 1 2 3 4 5 6 7]
row2:  [ 8  9 10 11 12 13 14 15]
row2:  [16 17 18 19 20 21 22 23]
row2:  [24 25 26 27 28 29 30 31]
row2:  [32 33 34 35 36 37 38 39]
row2:  [40 41 42 43 44 45 46 47]
row2:  [48 49 50 51 52 53 54 55]
row2:  [56 57 58 59 60 61 62 63]
